public class AuntBerthaDataWrapper {

	public class Programs {
		public List<String> attribute_tags;
		public String availability;
		public Central_hours_of_operation central_hours_of_operation;
		public String coverage_description;
		public String description;
		public String directions;
		public Double distance;
		public String entry_date;
		public String facebook_url;
		public String free_or_reduced;
		public String google_plus_id;
		public String grain;
		public List<String> grain_location;
		public String id;
		public Boolean isOfficeAvailable;
		public String name;
		public List<Next_steps> next_steps;
		public List<Offices> offices;
		public String program_numeric_id;
		public String provider_name;
		public String provider_numeric_id;
		public Double score;
		public List<String> service_tags;
		public List<String> supported_languages;
		public String twitter_id;
		public String update_date;
		public String validation_date;
		public String video_url;
		public String website_url;
		public Double wl_score;
		public List<String> rules;
		public List<Rule_attributes> rule_attributes;
	}

	public class Attribute_tag_counts {
		public List<Children> children;
		public String name;
		public String count;
	}

	public class Hours {
		public Boolean friday;
		public Boolean friday_all_day;
		public String friday_finish;
		public String friday_start;
		public Boolean monday;
		public Boolean monday_all_day;
		public String monday_finish;
		public String monday_start;
		public Boolean saturday;
		public Boolean saturday_all_day;
		public String saturday_finish;
		public String saturday_start;		
		public Boolean sunday;
		public Boolean sunday_all_day;
		public String sunday_finish;
		public String sunday_start;		
		public Boolean thursday;
		public Boolean thursday_all_day;
		public String thursday_finish;
		public String thursday_start;
		public String timezone;
		public String timezone_name;
		public String timezone_offset;
		public Boolean tuesday;
		public Boolean tuesday_all_day;
		public String tuesday_finish;
		public String tuesday_start;
		public Boolean wednesday;
		public Boolean wednesday_all_day;
		public String wednesday_finish;
		public String wednesday_start;
	}

	public class Postal_location {
		public Double latitude;
		public Double longitude;
	}

	public class Offices_S {
		public String address1;
		public String city;
		public Double distance;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String notes;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Open_now_info {
		public String close_time;
		public String day_of_the_week;
		public Boolean open_all_day;
		public Boolean open_now;
		public String open_time;
	}

	public class Offices_R {
		public String address1;
		public String address2;
		public String city;
		public Double distance;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Offices_U {
		public String address1;
		public String address2;
		public String city;
		public Double distance;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String notes;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Offices_T {
		public String address1;
		public String address2;
		public String city;
		public Double distance;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String notes;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
		public String phone_number;
	}

	public class Friday_Z {
	}

	public class Offices_W {
		public String address1;
		public String city;
		public Double distance;
		public String fax_number;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String notes;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
		public String address2;
	}

	public class Offices_V {
		public String address1;
		public String address2;
		public String city;
		public Double distance;
		public String email;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Offices_Y {
		public String address1;
		public String city;
		public Double distance;
		public String fax_number;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
		public String website_url;
	}

	public class Offices_X {
		public String address1;
		public String address2;
		public String city;
		public Double distance;
		public String email;
		public String fax_number;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Offices_Z {
		public String address1;
		public String city;
		public Double distance;
		public String email;
		public String fax_number;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String notes;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public class Rule_attributes {
		public String rule_comparison;
		public String rule_max_age;
		public String rule_min_age;
		public String rule_subtype;
		public String rule_type;
	}

	public class Friday {
		public Boolean open;
		public Boolean open_all_day;
	}

	public class Children {
		public String count;
		public String name;
	}

	public class Next_steps {
		public String action;
		public String channel;
		public String contact;
	}

	public class Central_hours_of_operation {
		public Friday friday;
		public Friday monday;
		public Friday saturday;
		public Friday sunday;
		public Friday thursday;
		public Friday tuesday;
		public Friday wednesday;
	}

	public class Central_hours_of_operation_Z {
		public Friday_Z friday;
		public Friday_Z monday;
		public Friday_Z saturday;
		public Friday_Z sunday;
		public Friday_Z thursday;
		public Friday_Z tuesday;
		public Friday_Z wednesday;
	}

	public class Offices {
		public String address1;
		public String city;
		public Double distance;
		public String email;
		public String fax_number;
		public Hours hours;
		public Boolean is_administrative;
		public Postal_location location;
		public String name;
		public String office_numeric_id;
		public List<String> office_type;
		public Open_now_info open_now_info;
		public String phone_number;
		public String postal;
		public String state;
		public List<String> supported_languages;
		public String url_safe_key;
	}

	public List<Attribute_tag_counts> attribute_tag_counts;
	public String count;
	public Postal_location postal_location;
	public List<Programs> programs;

	
	public static AuntBerthaDataWrapper parse(String json) {
		return (AuntBerthaDataWrapper) System.JSON.deserialize(json, AuntBerthaDataWrapper.class);
	}
}