name: Verifies Sample Data

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}

jobs:
  unit_tests:
    name: 'Verify sample data'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
          ./sfdx/install
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - run: |
          cci task run robot --org dev -o vars BROWSER:headlesschrome
      - name: Store robot results
        uses: actions/upload-artifact@v1
        with:
          name: robot
          path: robot/01HousingandHomelessness/results
      - name: Delete scratch org
        if: always()
        run: |
          cci org scratch_delete dev
